- name: Init new cloud server
  hosts: vps
  become: yes
  tasks:

    - name: Create ansible user
      user: 
        name: ansible
        group: sudo
        state: present

    - name: Add ssh key
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Replace debian user with ansible
      lineinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        regex: "debian"
        line: "ansible ALL (ALL:ALL) NOPASS"
