- name: Restart SSH
  systemd:
    name: sshd
    state: restarted

- name: Restart NFS
  systemd:
    name: nfs-kernel-server
    state: restarted

- name: restart wireguard
  shell: wg-quick down /etc/wireguard/wg0.conf && wg-quick up /etc/wireguard/wg0.conf

- name: Reload Daemon
  systemd:
    daemon_reload: true
